### ISSUE TITLE
Camera is requesting for microphone permissions even when is not being used

### ISSUE THREAD

**Issue by carloscacua** [Adbhutashra26/Multiple-Image-Camera#2]
`_controller = CameraController(
        _cameras[0],
        ResolutionPreset.ultraHigh,
      );`

**Comment by carloscacua** [comment]
It will be fixed with this PR 
https://github.com/Adbhutashra26/Multiple-Image-Camera/pull/3

**Comment by Adbhutashra** [comment]
I will update your pull request in the next version , Thanks !!
